### ISSUE TITLE
cannot import name 'six' from django.utils

### ISSUE THREAD

**Issue by kailashchoudhary11** [carltongibson/django-filter#1518]
I am using django 3.2.14 and I'm getting this error after adding 'django_filters' to the installed apps.
```Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed  File "E:\New folder\drf\geeky\gs18\venv\lib\site-packages\django_filters\__init__.py", line 7, in <module>
    from .filterset import FilterSet
  File "E:\New folder\drf\geeky\gs18\venv\lib\site-packages\django_filters\filterset.py", line 10, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (E:\New folder\drf\geeky\gs18\venv\lib\site-packages\django\utils\__init__.py)``` Let me know about the solutions

**Comment by carltongibson** [comment]
That import was removed in ace6df21f6379a854f055a691c2a4c5e863b2436 in 2017. I'd suggest you update django-filter.
