### ISSUE TITLE
Overriding ManyToManyFiled default widget

### ISSUE THREAD

**Issue by bluesurfer** [carltongibson/django-filter#404]
I am trying to override the default widget for a `ManyToManyField`. Following the docs I ended up with this:
```
class ProductFilter(django_filters.FilterSet):
    filter_overrides = {
        models.ManyToManyField: {
            'filter_class': django_filters.ModelMultipleChoiceFilter,
            'extra': lambda f: {
                'widget': forms.CheckboxSelectMultiple,
            },
        },
    }
```
But that gives me an error. Here's the traceback:

```
Traceback (most recent call last):
  File "/home/user/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/venv/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/user/venv/lib/python3.5/site-packages/django/contrib/auth/mixins.py", line 116, in dispatch
    return super(UserPassesTestMixin, self).dispatch(request, *args, **kwargs)
  File "/home/user/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/venv/lib/python3.5/site-packages/django_filters/views.py", line 61, in get
    self.object_list = self.filterset.qs
  File "/home/user/venv/lib/python3.5/site-packages/django_filters/filterset.py", line 321, in qs
    raw_value = self.form[name].value()
  File "/home/user/venv/lib/python3.5/site-packages/django_filters/filterset.py", line 364, in form
    for name, filter_ in six.iteritems(self.filters)])
  File "/home/user/venv/lib/python3.5/site-packages/django_filters/filterset.py", line 364, in <listcomp>
    for name, filter_ in six.iteritems(self.filters)])
  File "/home/user/venv/lib/python3.5/site-packages/django_filters/filters.py", line 121, in field
    help_text=help_text, **self.extra)
TypeError: __init__() missing 1 required positional argument: 'queryset'
```
How can I solve this?

**Comment by rpkilby** [comment]
`filter_overrides` completely overrides the default filter definition for a given model field. In this case, your `extra` function is missing `queryset`.

[default](https://github.com/carltongibson/django-filter/blob/v0.13/django_filters/filterset.py#L214-L220)
```py
    models.ManyToManyField: {
        'filter_class': ModelMultipleChoiceFilter,
        'extra': lambda f: {
            'queryset': remote_model(f)._default_manager.complex_filter(
                remote_field(f).limit_choices_to),
        }
    },
```
