### ISSUE TITLE
Filter DateTimeField by __date

### ISSUE THREAD

**Issue by prydie** [carltongibson/django-filter#436]
It doesn't look like `django-filter` currently supports filtering a `DateTimeField` by Django 1.9's new `__date` lookup expression.

```python
class SomeFilter(django_filters.FilterSet):
    class Meta:
        model = SomeModel
        fields = {
            'relation__created_at__date': ['gte', 'lt'],
            ...
        }
```

And I am getting the following `AttributeError`:

```
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 228, in patch_all
    patch_root_urlconf()
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 216, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 568, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in app_dict
    self._populate()
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 293, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/<redacted>/<redacted>/<redacted>/urls.py", line 41, in <module>
    url('^exports/', include('exports.urls')),
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/<redacted>/<redacted>/exports/urls.py", line 5, in <module>
    from . import views
  File "/home/vagrant/<redacted>/<redacted>/exports/views.py", line 15, in <module>
    from .filters import SomeFilter
  File "/home/vagrant/<redacted>/<redacted>/exports/filters.py", line 10, in <module>
    class SomeFilter(django_filters.FilterSet):
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django_filters/filterset.py", line 161, in __new__
    new_class.filter_for_reverse_field)
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django_filters/filterset.py", line 72, in filters_for_model
    field = get_model_field(model, f)
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django_filters/utils.py", line 54, in get_model_field
    opts = remote_model(rel)._meta
  File "/home/vagrant/.virtualenvs/<redacted>/local/lib/python2.7/site-packages/django_filters/compat.py", line 16, in remote_model
    return remote_field(field).model
AttributeError: 'NoneType' object has no attribute 'model'
```

**Comment by rpkilby** [comment]
Hi @prydie, use the following instead:

```py
class SomeFilter(django_filters.FilterSet):
    class Meta:
        model = SomeModel
        fields = {
            'relation__created_at': ['date__gte', 'date__lt'],
            ...
        }
```

The key is the model field to be filtered on. In this case, `date` is a lookup transform, which should be part of the `lookup_expr` on the right. More details in the [docs](https://django-filter.readthedocs.io/en/latest/usage.html#declaring-filters).

**Comment by prydie** [comment]
Thank you! That should have been obvious :blush:
