### ISSUE TITLE
Using global strictness setting

### ISSUE THREAD

**Issue by xuhcc** [carltongibson/django-filter#575]
It is not possible to define FILTERS_STRICTNESS setting without importing the django_filters package into the settings module.

However, when I do import, the following error occurs:

```
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "django/core/management/base.py", line 357, in execute
    translation.activate(saved_locale)
  File "django/utils/translation/__init__.py", line 161, in activate
    return _trans.activate(language)
  File "django/utils/translation/trans_real.py", line 238, in activate
    _active.value = translation(language)
  File "django/utils/translation/trans_real.py", line 227, in translation
    _translations[language] = DjangoTranslation(language)
  File "django/utils/translation/trans_real.py", line 129, in __init__
    self._add_installed_apps_translations()
  File "django/utils/translation/trans_real.py", line 171, in _add_installed_apps_translations
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
```

python 3.5
django 1.10
django-filter 1.0.0

**Comment by rpkilby** [comment]
Hi @xuhcc - for the short term, you can use the legacy `True`/`False`/`"RAISE"` values.
