### ISSUE TITLE
django_filters found on runserver, not on test

### ISSUE THREAD

**Issue by hmpf** [carltongibson/django-filter#707]
I'm trying to use the newest `django_filters` (1.0.2) with the newest `django_restframework` (3.6.2) on python3.4/django 1.11, and I also have `django-crispy-forms` (1.6.1) installed.

In order for crispyforms to find the form, I have `django_filters` in INSTALLED_APPS:
```
INSTALLED_APPS = (
    'rest_framework',
    'django_filters',
    'crispy_forms',
    'django_select2',
..
)
```

This works with `python manage runserver`, but not with `python manage test`. With the latter I get:

```
  File "$HOME/.virtualenvs/filtertest/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'django_filters'
```
I notice that `django_filters` doesn't have an `apps.py`, which may explain this... (but why only when testing?), so: What's the correct way of making this work?

**Comment by rpkilby** [comment]
This is hard to debug without more information. My guess is that there's a circular import loop. Do you have the full stack trace?

**Comment by hmpf** [comment]
Full, slightly anonymized stack trace:

```
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "$HOME/.virtualenvs/filtertest/lib/python3.4/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "$HOME/.virtualenvs/filtertest/lib/python3.4/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "$HOME/.virtualenvs/filtertest/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "$HOME/.virtualenvs/filtertest/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "$HOME/.virtualenvs/filtertest/lib/python3.4/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "$HOME/.virtualenvs/filtertest/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'django_filters'
```

I just double-checked: the tests are run with `python manage.py test`, with `tox`.

**Comment by rpkilby** [comment]
Just trying to think through some obvious cases first... are you sure that django-filter is installed to the tox env?

**Comment by carltongibson** [comment]
I don't think there's much we can say here. I suggest rebuilding a clean environment. Happy to help if we can come up with something concrete.

**Comment by nootmuskaat** [comment]
I realize this is closed but assuming this user was having the same issue I was, they probably installed 'django-filter**s**' and not 'django-filter'

**Comment by shayneoneill** [comment]
Ugh. Same problem. But I dont have django-filters installed, just django-filter
