### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by ramusus** [carltongibson/django-filter#759]
I've got error installing package
```
(env) ramusus@laptop:~/workspace$ pip install django-filter
Requirement already satisfied: django-filter in ./env/lib/python3.5/site-packages
Exception:
Traceback (most recent call last):
  File "/Users/ramusus/workspace/walltreks/env/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/ramusus/workspace/walltreks/env/lib/python3.5/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Users/ramusus/workspace/walltreks/env/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/ramusus/workspace/walltreks/env/lib/python3.5/site-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/Users/ramusus/workspace/walltreks/env/lib/python3.5/site-packages/pip/utils/packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/feedparser.py", line 177, in feed
    self._input.push(data)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/feedparser.py", line 101, in push
    parts = data.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'

(env) ramusus@laptop:~/workspace$ python
Python 3.5.2 (default, Oct 11 2016, 04:59:56) 

(env) ramusus@laptop:~/workspace$ pip --version
pip 9.0.1 from /Users/ramusus/workspace/walltreks/env/lib/python3.5/site-packages (python 3.5)
```

**Comment by ramusus** [comment]
That's strange but I solve this easily
```
(env) ramusus@laptop:~/workspace/walltreks$ rm -Rf ./env/lib/python3.5/site-packages/django_filter-1.0.4.dist-info/
(env) ramusus@laptop:~/workspace/walltreks$ pip install django-filter
Collecting django-filter
  Using cached django_filter-1.0.4-py2.py3-none-any.whl
Installing collected packages: django-filter
Successfully installed django-filter-1.0.4
```
