### ISSUE TITLE
Filter on nested ManyToMany

### ISSUE THREAD

**Issue by linkdd** [carltongibson/django-filter#779]
In my data model, I need to filter a set of rows according to a user which is accessed through a nested ManyToMany relationship.

Here is my model (simplified version):

```python
from django.contrib.auth.models import Group
from django.db import models

class MyModel(models.Model):
    roles = models.ManyToManyField(Group)
```

Here is my filter:

```python
class MyFilter(FilterSet):
    class Meta:
        model = MyModel
        fields = ('roles__user_set')
```

While this work fine to filter on simple ManyToMany relationships (as seen in the unit tests and in several other cases of my code), I get the following error when I try the same on a nested ManyToMany relationship.

Here my model has a M2M to the Group model, which as a M2M to the User model.

The actual error: ``TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: roles__user_set``

And with the traceback:

```
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f55f4920a60>
Traceback (most recent call last):
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/myuser/myprojectdir/myproject/myproject/urls.py", line 7, in <module>
    from myproject.apps.projects import views as project_views
  File "/home/myuser/myprojectdir/myproject/myproject/apps/projects/views.py", line 1, in <module>
    from myproject.apps.projects import models, serializers, filters
  File "/home/myuser/myprojectdir/myproject/myproject/apps/projects/filters.py", line 5, in <module>
    class ProjectFilter(FilterSet):
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django_filters/filterset.py", line 86, in __new__
    new_class.base_filters = new_class.get_filters()
  File "/home/myuser/myprojectdir/myproject/venv/lib/python3.5/site-packages/django_filters/filterset.py", line 313, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: roles__user_set
```

**Comment by linkdd** [comment]
It seems like it's not a ``django-filter`` issue.

Django itself is not capable of filtering in such a way.

**Comment by linkdd** [comment]
Another last comment, as I just saw my error.

The related name was ``user``, and not ``user_set``, so the filter needs to be ``roles__user``.
