### ISSUE TITLE
code no longer working for unexpected keyword argument error

### ISSUE THREAD

**Issue by yifan** [carltongibson/django-filter#948]
My code used to work, now tests start to fail. I am not sure why though. I think there is some compatibility issue with django-filter and django maybe? I couldn't figure it out. Please help.
```python
class ArticleFilter(filters.FilterSet):
  min_pub_date = DateTimeFilter(name='pub_date', lookup_expr='gte')
  max_pub_date = DateTimeFilter(name='pub_date', lookup_expr='lte')
  include_sources = NumbersInFilter(name='publisher__id', lookup_expr='in')
  exclude_sources = NumbersInFilter(name='publisher__id', lookup_expr='in', exclude=True)
  include_category = CharInFilter(name='category', lookup_expr='in')
  class Meta:
    model = Article
    fields = ['language', 'category', 'include_category', 'min_pub_date', 'max_pub_date', 'publisher__id', 'include_sources', 'exclude_sources']

class ArticleViewSet(viewsets.ReadOnlyModelViewSet):
  queryset = Article.objects.all()
  serializer_class = ArticleSerializer
  filter_class = ArticleFilter
```

versions:
```
defusedxml==0.5.0
Django==2.0.7
django-cors-headers==2.3.0
django-filter==2.0.0
django-nose==1.4.5
django-treenode==0.11.2
djangorestframework==3.8.2
drf-dynamic-fields==0.3.0
```

error:
```python
Traceback (most recent call last):
  File "tests.py", line 37, in test_articleviewset
    r = self.client.get(reverse('article-list')).json()
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django/test/client.py", line 517, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django/test/client.py", line 332, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django/test/client.py", line 404, in generic
    return self.request(**r)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django/test/client.py", line 485, in request
    raise exc_value
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/rest_framework/generics.py", line 152, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 94, in filter_queryset
    if not filterset.is_valid() and self.raise_exception:
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django_filters/filterset.py", line 206, in is_valid
    return self.is_bound and self.form.is_valid()
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django_filters/rest_framework/filterset.py", line 24, in form
    form = super().form
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django_filters/filterset.py", line 258, in form
    Form = self.get_form_class()
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django_filters/filterset.py", line 250, in get_form_class
    for name, filter_ in self.filters.items()])
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django_filters/filterset.py", line 250, in <listcomp>
    for name, filter_ in self.filters.items()])
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django_filters/filters.py", line 138, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django_filters/fields.py", line 159, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/xxxxxx/.local/share/virtualenvs/datastorage-Go_Yw_v3/lib/python3.6/site-packages/django/forms/fields.py", line 214, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'name'
```

**Comment by rpkilby** [comment]
Hi @yifan. Version 1.1.0 had a number of deprecations, including renaming the `name` argument to `field_name`. 

I would suggest installing django-filter v1.1.0 and [running your test suite with warnings enabled](http://django-filter.readthedocs.io/en/master/guide/migration.html#enabling-warnings) to view all deprecations. Once the issues are resolved, upgrade to v2.0 and check the v2.0 [migration guide](http://django-filter.readthedocs.io/en/master/guide/migration.html#migrating-to-2-0), as there are a few other breaking changes.
