### ISSUE TITLE
Using __in with django-filters 1.1, DRF 3.8 and Django 1.11

### ISSUE THREAD

**Issue by rhelms** [carltongibson/django-filter#976]
Hi

I'm trying to use an __in filter with django-filters 1.1, DRF 3.8 and Django 1.11 under Python 2.

The URL has the form /contact_group/?contacts__in=12,34,56,78.
The ContactGroup model has a many to many with contacts.

The traceback is
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/generics.py", line 152, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/usr/local/lib/python2.7/dist-packages/django_filters/rest_framework/backends.py", line 54, in filter_queryset
    return filter_class(request.query_params, queryset=queryset, request=request).qs
  File "/usr/local/lib/python2.7/dist-packages/django_filters/rest_framework/filterset.py", line 50, in qs
    return super(FilterSet, self).qs
  File "/usr/local/lib/python2.7/dist-packages/django_filters/filterset.py", line 206, in qs
    if not self.form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 384, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 396, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "/usr/local/lib/python2.7/dist-packages/django_filters/widgets.py", line 215, in value_from_datadict
    return value.split(',')
AttributeError: 'list' object has no attribute 'split'
```

This appears to be coming from BaseCSVWidget when an attempt is made to split the value that is passed. The issue seems to be that the value is already a list when this split happens, with a value of [u'12,34,56,78']. 

The widget appears to be a `django.utils.deprecation.CSVSelectMultiple` object.

I'm going to keep digging to see if I can work out how `django.utils.deprecation.CSVSelectMultiple` is selected, and if that is the cause for the value being a list from the start.

Either the value should not be initially interpretted as a list, or the BaseCSVWidget may need to cater for instances where the value is already a list (but the wrong type of list), and perform a split on the first entry in that list. I'm not sure if there's a scenario where that value would have multiple items in the list.

**Comment by rhelms** [comment]
I've done a bit more digging, but there are things happening that I can't quite see where they're coming from.

For instance, the field representing contacts__in appears to be dynamically generated to use `django_filters.filters.ModelMultipleChoiceInField`, but I can't see a definition for that.

I tried doing a monkey patch on django_filters.widgets.BaseCSVWidget.value_from_datadict to return the first value in `value` if `value` was a list. However, that didn't work.

So I tried the other way. That is, to only do the split if the `value` is a `six.string_types`. However, that falls over in the clean method, which ends up calling django_filters.field.BaseCSVField.clean, which calls clean for each value in `value`. This ends up calling clean on django.forms.models.ModelMultipleChoiceField, which throws an error if the if the value is not a list or tuple.

This may suggest that if the field is a multiple choice field, then there may not be a need to split the values in django_filters.field.BaseCSVField.clean. and just send the value through to the parent as one clean operation. I'm not sure where that leaves CSV fields that are not multiple choice.

I'm going to see if I can work some more magic, and see if there's a workaround for where I'm at now.

**Comment by rhelms** [comment]
Looking around a bit more, it would seem that this has never supported __in operations with many to many relationships.

I'm going to leave this open, unless there's a definitive statement to say that __in is not supported for many to many relationships.

**Comment by rpkilby** [comment]
That's amusing - I don't think the CSV filter was tested against m2m fields. 

Basically, the CSV filter works by mixing it's behavior with a concrete filter. This works for `CharFilter`, where the data type is a single value, but does not make sense for multiple choice fields, where you would have a list of values.

If you need an `contacts__in` filter, you'll need to declare this manually on the filterset class. Alternatively,  you can use `contacts`, which is a `ModelMultipleChoiceFilter`. The syntax would be different however.

**Comment by rhelms** [comment]
That's put me on the right path.  I was assuming that I'd have to use `in` to be able to do OR operations.

However, if I just use `contacts` and specify the query params in the long form (`contacts=1&contacts=2&contacts=3`), the query does exactly as I need it to.

**Comment by jsmedmar** [comment]
This used to work before when using `RelatedFilter`. If you are using `RelatedFilter`, you can use `contacts__pk__in=1,2,3`. I think `contacts__in=1,2,3` should work.

**Comment by jsmedmar** [comment]
We shouldn't close this issue. if `contacts__in` is not supported - it should be autogenerated in the first place? Would like to contribute but have no clue where to get started. Also Django supports `Contact.objects.filter(projects__in=[1, 2])`. So seems that `contacts__in` is a filter that makes sense to generate. What do you think @rpkilby?

**Comment by rpkilby** [comment]
@jsmedmar `RelatedFilter` is a subclass of `ModelChoiceFilter`, so shouldn't have an issue. That said, csv filtering is broken against m2m fields. I'll open a new issue for this.
